# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: Default
  

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  docker-file: 'Shopping/Shopping.API/Dockerfile'

steps:
- task: DockerCompose@1
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'my-public-docker-hub'
    dockerComposeFile: '**/docker-compose.yml'
    additionalDockerComposeFiles: '**/docker-compose.override.yml'
    action: 'Push services'
    includeSourceTags: true
    includeLatestTag: true